# https://github.com/Arduino-CI/arduino_ci/issues/159
# copied from vendor/bundle/ruby/2.6.0/gems/arduino_ci-0.3.0/misc/default.yml
platforms:
    mega2560:
      board: arduino:avr:mega:cpu=atmega2560
      package: arduino:avr
      gcc:
        features:
        defines:
          - __AVR_ATmega2560__
          - ARDUINO_CI
          - __AVR__
        warnings:
        flags:
  
unittest:
    platforms:
        - mega2560
    libraries:
      - "LiquidCrystal"
      - "RTClib"
      - "Adafruit BusIO"
      - "Adafruit MAX31865"

compile:
    platforms:
      - mega2560
    libraries:
      - "LiquidCrystal"
      - "RTClib"
      - "Adafruit BusIO"
      - "Adafruit MAX31865"

